### ISSUE TITLE
Does not work when Kubernetes has RBAC

### ISSUE THREAD

**Issue by kyomster** [estafette/estafette-cloudflare-dns#6]
Hello,

When trying to deploy on Kubernetes with RBAC I get:

{"time":"2017-11-08T22:03:56Z","severity":"error","app":"estafette-cloudflare-dns","version":"1.0.103","error":"kubernetes api: Failure 403 services is forbidden: User \"system:serviceaccount:default:default\" cannot list services at the cluster scope","message":"ListServices call failed"}

Is there a workaround ?

**Comment by etiennetremel** [comment]
Hi @kyomster, looks like the documentation is not up to date, I 'm going to update it later today. 

Until the fix come through, you have to manually create a service account:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: estafette-cloudflare-dns
  namespace: estafette
```

Then add the `serviceAccount: estafette-cloudflare-dns` field to the deployment manifest, see:
https://github.com/estafette/estafette-cloudflare-dns/blob/master/kubernetes.yaml#L41

Let me know if you are still running into trouble/
